# -*- coding: utf-8 -*-
"""K-Nearest Neighbour .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13UtmtodippbnYSz3I3rJjhQqjXN3E5LG
"""

import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np 
import seaborn as sns 

from google.colab import drive 
drive.mount('/content/drive')

data = pd.read_csv("/content/drive/MyDrive/data.csv")

data.head()

data.info()

data.drop(["Unnamed: 32","id"],axis=1, inplace=True)

M = data[data.diagnosis=="M"]
B = data[data.diagnosis=="B"]

M.info()

B.info()

plt.scatter(M.radius_mean,M.area_mean,color="red",label="malignant")
plt.scatter(B.radius_mean,B.area_mean,color="green",label="benign")
plt.legend() 
plt.xlabel("radius_mean")
plt.ylabel("area_mean")
plt.show()

plt.scatter(M.radius_mean,M.texture_mean,color="red",label="malignant") 
plt.scatter(B.radius_mean,B.texture_mean,color="green",label="benign")
plt.xlabel("radius_mean")
plt.ylabel("texture_mean")
plt.legend()
plt.show()

data.diagnosis = [1 if each=="M" else 0 for each in data.diagnosis]

y = data.diagnosis.values

x_data= data.iloc[:,1:3].values

x = (x_data - np.min(x_data))/(np.max(x_data) - np.min(x_data))

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=1)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(x_train,y_train)

y_head = knn.predict(x_test)
y_head

print("when k is {}, accuracy of knn classification {} ".format(3,knn.score(x_test,y_test)))

test_accuracy = []
for each in range(1,15):
    knn2 = KNeighborsClassifier(n_neighbors = each)
    knn2.fit(x_train,y_train)
    test_accuracy.append(knn2.score(x_test,y_test))
    
plt.figure(figsize=(5,5))
plt.plot(range(1,15),test_accuracy)
plt.title('K Values VS Accuracy')
plt.xlabel("k values")
plt.ylabel("accuracy")
plt.grid()
plt.show()
print("Best accuracy is {} with K = {}".format(np.max(test_accuracy),1+test_accuracy.index(np.max(test_accuracy))))

error = []
for i in range (1,40):
  knn= KNeighborsClassifier(n_neighbors=i)
  knn.fit(x_train,y_train)
  pred_i = knn.predict(x_test)
  error.append(np.mean(pred_i != y_test))

plt.figure(figsize=(12,6))
plt.plot(range(1,40), error, color='red',linestyle='dashed',marker='o',markerfacecolor='blue',markersize=10)
plt.title('Error Rate K Value')
plt.xlabel('K Value')
plt.ylabel('Mean Error')
plt.grid()
plt.show()

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_head)

f,ax = plt.subplots(figsize=(5, 5))
sns.heatmap(cm,annot=True,fmt= '.0f',linewidths=0.5,linecolor="red",ax=ax)
plt.xlabel("y_pred")
plt.ylabel("y_test")
plt.show()